sudo: required

language: node_js
node_js:
  - "7"
services:
  - docker
before_script:
  - npm install -g @angular/cli

script:
  - $(npm bin)/ng build --prod --build-optimizer --aot --locale fr --i18n-file src/locale/messages.fr.xtb --i18n-format xtb

notifications:
  email:
    on_failure: change
    on_success: change


after_success:
  - docker login -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD" docker.io
  - docker build -t 'pushmyshop/pushmyshop-market:latest' .
  - docker push pushmyshop/pushmyshop-market:latest