sudo: required
apt:
 sources:
 — google-chrome
 packages:
 — google-chrome-stable
 — google-chrome-beta
 
language: node_js
node_js:
  - "7"
services:
  - docker
before_install:
 — export CHROME_BIN=chromium-browser
 — export DISPLAY=:99.0
 — sh -e /etc/init.d/xvfb start


install:
  - npm install

after_success:
  - docker login -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD" docker-io
  - docker build -t 'pushmyshop/pushmyshop-market:latest' .
  - docker push pushmyshop/pushmyshop-market:latest